version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL:-https://api.luckygas.tw}
        VITE_WS_URL: ${VITE_WS_URL:-wss://api.luckygas.tw}
        VITE_ENV: ${VITE_ENV:-production}
        VITE_GOOGLE_MAPS_API_KEY: ${VITE_GOOGLE_MAPS_API_KEY:-}
        VITE_SENTRY_DSN: ${VITE_SENTRY_DSN:-}
    image: luckygas-frontend:${VERSION:-latest}
    container_name: luckygas-frontend
    ports:
      - "${FRONTEND_PORT:-80}:80"
    environment:
      - NGINX_PORT=80
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - luckygas-network

networks:
  luckygas-network:
    driver: bridge