version: '3.8'

services:
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_SERVER: host.docker.internal
      ADMINER_DESIGN: pepa-linha-dark