# Gitleaks configuration for detecting secrets
title = "gitleaks config"

# Redact secrets in output
[redact]
enabled = true

# Google API Key Detection
[[rules]]
id = "google-api-key"
description = "Google API Key"
regex = '''AIza[0-9A-Za-z\\-_]{35}'''
tags = ["key", "Google"]

# Generic API Key Detection
[[rules]]
id = "generic-api-key"
description = "Generic API Key"
regex = '''(?i)(api_key|apikey|api-key)\s*[:=]\s*['"][0-9a-zA-Z_\-]{16,}['"]'''
tags = ["key", "API"]

# Private Key Detection
[[rules]]
id = "private-key"
description = "Private Key"
regex = '''-----BEGIN (RSA|EC|DSA) PRIVATE KEY-----'''
tags = ["key", "private"]

# JWT Token Detection
[[rules]]
id = "jwt"
description = "JWT Token"
regex = '''eyJ[A-Za-z0-9_/+-]*\.[A-Za-z0-9_/+-]*\.[A-Za-z0-9_/+-]*'''
tags = ["token", "jwt"]

# Allow list - paths to ignore
[allowlist]
paths = [
  "**/.gitleaks.toml",
  "**/test/**",
  "**/*_test.go",
  "**/*.md"
]