apiVersion: apps/v1
kind: Deployment
metadata:
  name: luckygas-backend
  namespace: luckygas
spec:
  replicas: 5
  template:
    spec:
      containers:
      - name: backend
        resources:
          requests:
            cpu: "500m"
            memory: "1Gi"
          limits:
            cpu: "2000m"
            memory: "4Gi"
        env:
        - name: WORKERS
          value: "8"
        - name: DATABASE_POOL_SIZE
          value: "50"
        - name: DATABASE_MAX_OVERFLOW
          value: "20"
        - name: REDIS_MAX_CONNECTIONS
          value: "100"
      nodeSelector:
        workload-type: api
      tolerations:
      - key: workload-type
        operator: Equal
        value: api
        effect: NoSchedule