# Canary Deployment Configuration for LuckyGas
# Enables gradual traffic migration to new versions

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: luckygas-backend-canary
  namespace: default
  labels:
    app: luckygas-backend
    version: canary
spec:
  replicas: 2  # Start with minimal replicas
  selector:
    matchLabels:
      app: luckygas-backend
      version: canary
  template:
    metadata:
      labels:
        app: luckygas-backend
        version: canary
    spec:
      serviceAccountName: luckygas-backend
      containers:
      - name: backend
        image: gcr.io/lucky-gas-prod/backend:canary
        ports:
        - containerPort: 8000
        env:
        - name: ENV
          value: "production"
        - name: VERSION
          value: "canary"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: database-credentials
              key: url
        - name: GOOGLE_MAPS_API_KEY
          valueFrom:
            secretKeyRef:
              name: google-api-keys
              key: maps
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: jwt-secret
              key: secret
        - name: REDIS_URL
          value: "redis://redis:6379/0"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: luckygas-frontend-canary
  namespace: default
  labels:
    app: luckygas-frontend
    version: canary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: luckygas-frontend
      version: canary
  template:
    metadata:
      labels:
        app: luckygas-frontend
        version: canary
    spec:
      serviceAccountName: luckygas-frontend
      containers:
      - name: frontend
        image: gcr.io/lucky-gas-prod/frontend:canary
        ports:
        - containerPort: 3000
        env:
        - name: REACT_APP_API_URL
          value: "https://api.luckygas.com.tw"
        - name: REACT_APP_GOOGLE_MAPS_KEY
          valueFrom:
            secretKeyRef:
              name: google-api-keys
              key: maps
        - name: VERSION
          value: "canary"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5

---
# Service for canary backend
apiVersion: v1
kind: Service
metadata:
  name: luckygas-backend-canary
  namespace: default
spec:
  selector:
    app: luckygas-backend
    version: canary
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP

---
# Service for canary frontend
apiVersion: v1
kind: Service
metadata:
  name: luckygas-frontend-canary
  namespace: default
spec:
  selector:
    app: luckygas-frontend
    version: canary
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP