# Traffic Split Configuration for Canary Deployment
# Uses Istio VirtualService for gradual traffic migration

---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: luckygas-vs
  namespace: default
spec:
  hosts:
  - api.luckygas.com.tw
  - app.luckygas.com.tw
  http:
  # API Traffic Rules
  - match:
    - uri:
        prefix: "/api/"
      headers:
        host:
          exact: api.luckygas.com.tw
    route:
    - destination:
        host: luckygas-backend
        port:
          number: 80
      weight: 100  # Start with 100% to stable
    - destination:
        host: luckygas-backend-canary
        port:
          number: 80
      weight: 0    # 0% to canary initially
    
  # Frontend Traffic Rules
  - match:
    - headers:
        host:
          exact: app.luckygas.com.tw
    route:
    - destination:
        host: luckygas-frontend
        port:
          number: 80
      weight: 100  # Start with 100% to stable
    - destination:
        host: luckygas-frontend-canary
        port:
          number: 80
      weight: 0    # 0% to canary initially

---
# DestinationRule for load balancing
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: luckygas-backend-dr
  namespace: default
spec:
  host: luckygas-backend
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 100
      http:
        http1MaxPendingRequests: 100
        http2MaxRequests: 100
        maxRequestsPerConnection: 5
    loadBalancer:
      simple: ROUND_ROBIN
  subsets:
  - name: stable
    labels:
      version: stable
  - name: canary
    labels:
      version: canary

---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: luckygas-frontend-dr
  namespace: default
spec:
  host: luckygas-frontend
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 100
      http:
        http1MaxPendingRequests: 100
        http2MaxRequests: 100
    loadBalancer:
      simple: ROUND_ROBIN
  subsets:
  - name: stable
    labels:
      version: stable
  - name: canary
    labels:
      version: canary

---
# ServiceMonitor for Prometheus to track canary metrics
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: luckygas-canary-metrics
  namespace: default
spec:
  selector:
    matchLabels:
      app: luckygas-backend
      version: canary
  endpoints:
  - port: metrics
    interval: 30s
    path: /metrics

---
# PodDisruptionBudget to ensure availability during migration
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: luckygas-backend-canary-pdb
  namespace: default
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: luckygas-backend
      version: canary

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: luckygas-frontend-canary-pdb
  namespace: default
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: luckygas-frontend
      version: canary