# GCP Deployment Configuration for LuckyGas v3.0
# Production deployment settings for asia-east1 region

project_id: vast-tributary-466619-m8
region: asia-east1
zone: asia-east1-a

# Cloud SQL Configuration
database:
  instance_name: luckygas-prod-db
  tier: db-n1-standard-2  # 2 vCPU, 7.5GB RAM
  database_version: POSTGRES_15
  storage_size: 100  # GB
  storage_type: SSD
  backup:
    enabled: true
    start_time: "03:00"  # 3 AM Taiwan time (UTC+8)
    location: asia-east1
    retention_days: 30
  maintenance:
    day: 7  # Sunday
    hour: 4  # 4 AM
    update_track: stable
  high_availability:
    enabled: true
    zone: asia-east1-b
  flags:
    max_connections: "200"
    shared_buffers: "256MB"
    effective_cache_size: "4GB"
    maintenance_work_mem: "256MB"

# Cloud Run Configuration  
cloud_run:
  service_name: luckygas-backend
  memory: 2Gi
  cpu: "2"
  min_instances: 1
  max_instances: 10
  concurrency: 100
  timeout: 300
  port: 8080
  vpc_connector: luckygas-vpc-connector
  ingress: all
  
# Redis/Memorystore Configuration
redis:
  instance_name: luckygas-cache
  tier: STANDARD
  memory_size: 1  # GB
  redis_version: REDIS_6_X
  auth_enabled: true
  tls_enabled: true
  
# Cloud Storage Configuration
storage:
  frontend_bucket: luckygas-frontend-prod
  backup_bucket: luckygas-backups-prod
  location: asia-east1
  storage_class: STANDARD
  lifecycle:
    - action: Delete
      condition:
        age: 90  # Delete backups older than 90 days
        
# Secret Manager Configuration
secrets:
  - name: database-password
  - name: jwt-secret-key
  - name: first-superuser-password
  - name: redis-password
  - name: vertex-ai-key
  - name: maps-api-key
  - name: sms-api-key
  - name: banking-api-key

# Cloud Build Configuration
cloud_build:
  trigger_name: luckygas-main-trigger
  github_repo: LuckyGas-v3
  branch: main
  dockerfile: backend/Dockerfile.production
  
# Monitoring Configuration
monitoring:
  notification_channels:
    - type: email
      email: admin@luckygas.com.tw
  alerts:
    - name: high-response-time
      condition: response_time > 500ms
      duration: 5m
    - name: high-error-rate
      condition: error_rate > 0.02
      duration: 5m
    - name: instance-health
      condition: healthy_instances < 1
      duration: 2m
      
# Load Balancer Configuration
load_balancer:
  name: luckygas-lb
  ssl_certificate: luckygas-ssl-cert
  domains:
    - api.luckygas.com.tw
    - luckygas.com.tw
  cdn_enabled: true
  
# Cost Optimization Settings
cost_optimization:
  auto_pause_dev: true  # Pause dev instances when not in use
  committed_use_discount: false  # Enable for long-term savings
  preemptible_instances: false  # Not for production