apiVersion: v1
kind: ConfigMap
metadata:
  name: luckygas-backend-config
  namespace: luckygas
  labels:
    app.kubernetes.io/name: luckygas-backend
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: luckygas-system
data:
  # Application configuration
  APP_NAME: "LuckyGas Delivery System"
  ENVIRONMENT: "production"
  DEBUG: "false"
  LOG_LEVEL: "INFO"
  
  # API configuration
  API_V1_PREFIX: "/api/v1"
  CORS_ORIGINS: '["https://luckygas.com.tw", "https://www.luckygas.com.tw", "https://app.luckygas.com.tw"]'
  
  # Database configuration (non-sensitive)
  DATABASE_HOST: "postgres-service.luckygas.svc.cluster.local"
  DATABASE_PORT: "5432"
  DATABASE_NAME: "luckygas"
  DATABASE_POOL_SIZE: "20"
  DATABASE_MAX_OVERFLOW: "10"
  
  # Redis configuration
  REDIS_HOST: "redis-service.luckygas.svc.cluster.local"
  REDIS_PORT: "6379"
  REDIS_DB: "0"
  
  # Google Cloud configuration
  GCP_PROJECT_ID: "luckygas-production"
  GCP_REGION: "asia-east1"
  GOOGLE_MAPS_LANGUAGE: "zh-TW"
  GOOGLE_MAPS_REGION: "TW"
  
  # Monitoring
  ENABLE_METRICS: "true"
  METRICS_PORT: "9090"
  
  # Security
  JWT_ALGORITHM: "HS256"
  JWT_ACCESS_TOKEN_EXPIRE_MINUTES: "30"
  JWT_REFRESH_TOKEN_EXPIRE_DAYS: "7"
  
  # Taiwan-specific settings
  DEFAULT_TIMEZONE: "Asia/Taipei"
  DEFAULT_LOCALE: "zh-TW"
  CURRENCY: "TWD"
  
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: luckygas-frontend-config
  namespace: luckygas
  labels:
    app.kubernetes.io/name: luckygas-frontend
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: luckygas-system
data:
  # Nginx configuration
  nginx.conf: |
    user nginx;
    worker_processes auto;
    error_log /var/log/nginx/error.log warn;
    pid /var/run/nginx.pid;

    events {
        worker_connections 1024;
        use epoll;
        multi_accept on;
    }

    http {
        include /etc/nginx/mime.types;
        default_type application/octet-stream;

        # Logging
        log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                        '$status $body_bytes_sent "$http_referer" '
                        '"$http_user_agent" "$http_x_forwarded_for"';
        access_log /var/log/nginx/access.log main;

        # Performance
        sendfile on;
        tcp_nopush on;
        tcp_nodelay on;
        keepalive_timeout 65;
        types_hash_max_size 2048;
        client_max_body_size 20M;

        # Gzip compression
        gzip on;
        gzip_disable "msie6";
        gzip_vary on;
        gzip_proxied any;
        gzip_comp_level 6;
        gzip_types text/plain text/css text/xml text/javascript 
                   application/json application/javascript application/xml+rss 
                   application/rss+xml application/x-font-ttf font/opentype 
                   image/svg+xml image/x-icon;

        # Security headers
        add_header X-Frame-Options "SAMEORIGIN" always;
        add_header X-Content-Type-Options "nosniff" always;
        add_header X-XSS-Protection "1; mode=block" always;
        add_header Referrer-Policy "no-referrer-when-downgrade" always;
        add_header Content-Security-Policy "default-src 'self' https:; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://maps.googleapis.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https:; connect-src 'self' https://api.luckygas.com.tw wss://api.luckygas.com.tw https://maps.googleapis.com;" always;

        server {
            listen 8080;
            server_name _;
            root /usr/share/nginx/html;
            index index.html;

            # Health check endpoint
            location /health {
                access_log off;
                return 200 "healthy\n";
                add_header Content-Type text/plain;
            }

            # API proxy
            location /api {
                proxy_pass http://luckygas-backend-service:8000;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection 'upgrade';
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_cache_bypass $http_upgrade;
                proxy_connect_timeout 60s;
                proxy_send_timeout 60s;
                proxy_read_timeout 60s;
            }

            # WebSocket proxy
            location /ws {
                proxy_pass http://luckygas-backend-service:8000;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_read_timeout 86400;
            }

            # SPA routing
            location / {
                try_files $uri $uri/ /index.html;
                add_header Cache-Control "no-cache, no-store, must-revalidate";
                add_header Pragma "no-cache";
                add_header Expires "0";
            }

            # Static assets with long cache
            location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$ {
                expires 1y;
                add_header Cache-Control "public, immutable";
            }
        }
    }