apiVersion: v1
kind: Namespace
metadata:
  name: luckygas
  labels:
    app.kubernetes.io/name: luckygas
    app.kubernetes.io/part-of: luckygas-system
    environment: production
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: luckygas-quota
  namespace: luckygas
spec:
  hard:
    requests.cpu: "100"
    requests.memory: "200Gi"
    persistentvolumeclaims: "10"
    services: "20"
    services.loadbalancers: "2"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: luckygas-limits
  namespace: luckygas
spec:
  limits:
  - default:
      cpu: "2"
      memory: "4Gi"
    defaultRequest:
      cpu: "100m"
      memory: "128Mi"
    max:
      cpu: "4"
      memory: "8Gi"
    min:
      cpu: "50m"
      memory: "64Mi"
    type: Container
  - max:
      storage: "50Gi"
    type: PersistentVolumeClaim