apiVersion: v1
kind: ServiceAccount
metadata:
  name: luckygas-backend
  namespace: luckygas
  labels:
    app.kubernetes.io/name: luckygas-backend
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: luckygas-system
  annotations:
    iam.gke.io/gcp-service-account: luckygas-backend@luckygas-production.iam.gserviceaccount.com
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: luckygas-frontend
  namespace: luckygas
  labels:
    app.kubernetes.io/name: luckygas-frontend
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: luckygas-system
automountServiceAccountToken: false
---
# RBAC for backend service account
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: luckygas-backend-role
  namespace: luckygas
  labels:
    app.kubernetes.io/name: luckygas-backend
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: luckygas-system
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: luckygas-backend-rolebinding
  namespace: luckygas
  labels:
    app.kubernetes.io/name: luckygas-backend
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: luckygas-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: luckygas-backend-role
subjects:
- kind: ServiceAccount
  name: luckygas-backend
  namespace: luckygas