apiVersion: apps/v1
kind: Deployment
metadata:
  name: luckygas-backend
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: backend
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"
        env:
        - name: WORKERS
          value: "2"
        - name: MAX_REQUESTS
          value: "1000"
        - name: MAX_REQUESTS_JITTER
          value: "100"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: luckygas-frontend
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: frontend
        resources:
          requests:
            cpu: "50m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "512Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: luckygas-celery-worker
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: celery-worker
        args:
        - "-A"
        - "app.tasks"
        - "worker"
        - "--loglevel=debug"
        - "--concurrency=1"
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: luckygas-backend-hpa
spec:
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 85