apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: luckygas-staging

namePrefix: staging-

commonLabels:
  environment: staging
  app.kubernetes.io/managed-by: kustomize

bases:
- ../../base

patchesStrategicMerge:
- deployment-patches.yaml
- ingress-patch.yaml

configMapGenerator:
- name: luckygas-backend-config
  behavior: merge
  literals:
  - ENVIRONMENT=staging
  - LOG_LEVEL=debug
  - ALLOWED_HOSTS=staging.luckygas.com.tw,*.luckygas.com.tw
  - CORS_ALLOWED_ORIGINS=https://staging.luckygas.com.tw
  - DATABASE_POOL_SIZE=10
  - DATABASE_MAX_OVERFLOW=20
  - REDIS_URL=redis://luckygas-redis:6379/0
  - CLOUD_SQL_CONNECTION_NAME=luckygas-staging:asia-east1:luckygas-staging-db
  - GOOGLE_CLOUD_PROJECT=luckygas-staging
  - VERTEX_AI_LOCATION=asia-east1
  - ENABLE_PROFILING=true
  - ENABLE_DEBUG_TOOLBAR=true

secretGenerator:
- name: luckygas-backend-secrets
  behavior: merge
  envs:
  - secrets-staging.env

images:
- name: gcr.io/luckygas-production/luckygas-backend
  newName: gcr.io/luckygas-staging/luckygas-backend
  newTag: staging-latest
- name: gcr.io/luckygas-production/luckygas-frontend
  newName: gcr.io/luckygas-staging/luckygas-frontend
  newTag: staging-latest

replicas:
- name: luckygas-backend
  count: 2
- name: luckygas-frontend
  count: 2
- name: luckygas-celery-worker
  count: 1